BinaryStudioAcademy/bsa-2024-gitfit

- apps/backend/src/db/migrations/20240829181900_fix_user_groups_to_permissions.ts
Created new migration to change FK user_groups_to_permissions.permission_id to reference permissions.id
> fix: refactor user groups to permissions relation gf-78

- apps/frontend/src/modules/users/users-api.ts
Message was appearing because we couldn't get users due to lack of authorization token in the request. 
Solution: in `getAll` method of `UserApi`, while calling `load`, we need to pass `true` to `hasAuth` property of `options`, in order to include token to the request.
> fix: "No token provided" error message appears when navigating to the "Access Management" page gf-117

- apps/frontend/src/libs/components/button/styles.module.css
Done: 
- centralized text alignment on the button
Preview:
> fix: Inconsistent line height of the Back to home text within the button on the Not fount page gf-156

- apps/frontend/src/libs/components/table/styles.module.css
- apps/frontend/src/libs/components/table/table.tsx
Added scroll to the table. The header of the table is sticking at the top, while body is moving.
> feat: scroll element must be shown at the right side of the table component gf-149

- apps/frontend/src/pages/profile/profile.tsx
- apps/frontend/src/pages/profile/styles.module.css
- fix title font size and add additional settings (line-height, word-break)
- change profile layout styles
> fix: Font size of the "Profile" heading doesn`t match the design mockup gf-192

- apps/frontend/src/assets/images/icons/right-arrow.svg
Adjuested the SVG color icon  right-arrow.svg to not have fill="white" attribute in it's path, it now handles color values
> fix: adjustment of right arrow svg icon to handle custom color attributes gf-208

- apps/frontend/src/libs/components/table/styles.module.css
- apps/frontend/src/libs/components/table/table.tsx
* Added "There is nothing yet." display message for empty tables.
* Message is added as a single table row in a table with headers.
* Styles are consistent with "No projects found matching your search criteria. Please try different keywords." display message.
> feat: add display message for empty tables gf-206

- apps/backend/src/modules/groups/group.repository.ts
* Groups are ordered from old to new.
* Irrelevant total amount of items bug was fixed before.
(word-break and word-wrap are added in #268)
> fix: Incorrect group positioning in Groups table gf-266

- apps/frontend/src/libs/components/table/styles.module.css
- apps/frontend/src/libs/components/table/table.tsx
- apps/frontend/src/pages/access-management/libs/components/group-users-table/group-users-table.tsx
- apps/frontend/src/pages/access-management/libs/components/group-users-table/libs/helpers/get-group-users-columns.helper.ts
- apps/frontend/src/pages/access-management/libs/components/group-users-table/libs/helpers/helpers.ts
- apps/frontend/src/pages/access-management/libs/components/group-users-table/styles.module.css
* Added gap between table and table pagination.
* Refactored spacing between checkbox and name columns.
* Added word-break and word-wrap to table component to avoid overflow.
> fix: fix inconsistent alignment in create group modal gf-265

- packages/shared/src/modules/groups/libs/enums/group-validation-message.enum.ts
* Refactored group validation messages.
> fix: Invalid validation messages in Create group modal gf-262

- apps/frontend/src/pages/access-management/libs/helpers/get-user-columns.helper.ts
* Set fixed column sizes in users table according to mockup.
> fix: inconsistent layout of the users table gf-267

- apps/frontend/src/pages/project/project.tsx
- package-lock.json
Adjusted the path so it now leads to projects page instead of root
> fix: adjusted path for project page breadcrumbs gf-283

- apps/frontend/src/libs/components/table/styles.module.css
* Refactored table styles to break word only if it can't fit in entire line. Before it broke words even if they could fit perfectly on the next line.
> fix: Group and permission names are broken in the middle of a word gf-299

- apps/frontend/src/pages/projects/projects.tsx
- package-lock.json
Modified the logic for displaying the project status message to handle two cases:
- When no projects have been created: "No projects created yet. Create the first project now."
- When a search query returns no results: "No projects found matching your search criteria. Please try different keywords."
No Projects
No Projects
With projects
With Projects
> fix: adjusted project status message based on search state gf-313

- apps/backend/src/modules/projects/project.controller.ts
Restrict users from creating/editing/deleting groups on the backend.
> fix: restrict users to manage projects gf-324

- apps/frontend/src/pages/access-management/access-management.tsx
- package-lock.json
- packages/shared/src/modules/projects/libs/types/project-get-all-request-dto.type.ts
Updated group deletion logic to automatically refresh the table after deleting a group.
Made sure that pagination is working properly on deletion.
Table refreshing on delete
https://github.com/user-attachments/assets/22fef328-2d10-4c63-9889-0f3bcbf090ae
table changing page on delete
https://github.com/user-attachments/assets/e9b2ca33-34ac-43c9-8c9e-700322c05997
> fix: groups table refresh on deletion of group gf-329

- apps/frontend/src/libs/components/date-input/styles.module.css
Made future days visible with color of neighboring month. (They are disabled as well, user can not choose them). Also noticed a problem with bigger scale views and fixed it. (Looks like it came up after changes that were made now).
> fix: the last month in the calendar component on the analytics page is shown with empty data gf-357

- apps/frontend/src/pages/projects/projects.tsx
Implemented the emtyPlaceHolderMessage to handle the status message for projects, to fix the status message
Now it shows correctly each statement depending on search or no projects
> fix: implemented emtyplaceholdermessage to handle statusmessage for projects page gf-313

- apps/backend/src/modules/activity-logs/activity-log.service.ts
- apps/backend/src/modules/activity-logs/libs/exceptions/exceptions.ts
- packages/shared/src/libs/enums/exception-message.enum.ts
- packages/shared/src/modules/activity-logs/libs/enums/activity-log-validation-message.enum.ts
- packages/shared/src/modules/activity-logs/libs/validation-schemas/activity-log-create.validation-schema.ts
The "Failed to create activity log." error was added if the creation of new log goes wrong. Also the validation schema was fixed.
Earlier:
Now:
> fix: improve error handling in creating activity logs gf-332

- apps/backend/src/modules/project-groups/libs/helpers/generate-project-group-key.helper.ts
- apps/backend/src/modules/project-groups/libs/helpers/helpers.ts
- apps/backend/src/modules/project-groups/project-group.repository.ts
- apps/backend/src/modules/project-groups/project-group.service.ts
- packages/shared/src/libs/helpers/change-case/change-case.helper.ts
- unique project group key is fixed by adding project id
- changed checking of existing group
> fix: Make project group name unique only within the scope of a project gf-361

- apps/frontend/src/pages/project/libs/components/contributors-list/contributors-list.tsx
- apps/frontend/src/pages/project/libs/components/contributors-list/styles.module.css
Added a placeholder, which looks like this:
P.S. had to split conditions in order to get rid of linter problems. Linter does not allow to nest ternary expression without parentheses, but formatter wants that expression without them. If there is a better solution, please suggest it.
> feat: added placeholder to contributors list on project page gf-377

- apps/frontend/src/pages/project-access-management/libs/helpers/get-project-group-columns.helper.tsx
- apps/frontend/src/pages/project-access-management/libs/helpers/get-project-group-rows.helper.tsx
- apps/frontend/src/pages/project-access-management/libs/types/project-group-row.type.ts
- apps/frontend/src/pages/project-access-management/project-access-management.tsx
- added users column to groups table on project access management page.
> feat: add users column to groups table on project access management page gf-403

- apps/frontend/src/pages/project-access-management/libs/components/project-group-users-table/libs/helpers/get-group-users-columns.helper.ts
Now  the table looks like at the main Access Management page
Preview:
> fix: The Users table in the Create Projects Group Modal appearance is incorrect for the 1440px and 1024px screen resolution gf-389

- apps/frontend/src/pages/access-management/libs/helpers/get-user-columns/get-user-columns.helper.tsx
- Adjusted column sizes so the table fit 1440px screen resolution without horizontal scrollbar appeared
> fix: Inconsistent Users table resolution on the Access managment page on 1440px screen resolution gf-448

- apps/frontend/src/pages/project-access-management/libs/helpers/get-user-columns/get-user-columns.helper.ts
- Adjusted column size so table fits 1440px screen resolution without horizontal scroll appeared
> fix: Inconsistent Users table resolution on the Project Access managment page on 1440px screen resolution gf-448

- apps/frontend/src/pages/analytics/libs/components/analytics-table/analytics-table.tsx
Analytics table is full screen for high resolution (2560px)
> fix: inconsistent alignment of the analytics table on the analytics page gf-473

- apps/backend/src/modules/groups/group.repository.ts
- apps/backend/src/modules/project-groups/project-group.repository.ts
Fixed table updating after user deletion by filtering deleted users from the result of api response. 
Also this might be fixed by removing relations between deleted users and groups, but decided to do it the easier way. Additionally, if user account is recovered, his relations will be saved.
> fix: the total number of users is not updated in the groups table after deleting a user gf-463

- apps/frontend/src/pages/analytics/analytics.tsx
- apps/frontend/src/pages/analytics/libs/components/analytics-table/analytics-table.tsx
Moved the loader to the table to follow the style of the project.
> fix: loader component is not vertically centralized on the analytics page gf-471

- apps/frontend/src/libs/components/date-input/date-input.tsx
- apps/frontend/src/libs/components/date-input/styles.module.css
Fixed `DateInput` component
- change type of trigger button to `button`, so it does not trigger form submission
- add `cursor: pointer` style
- when popover opened, pressing button closes it
> fix: The table on the Analytics page reloads after a click on the date input to open the calendar gf-472

- apps/frontend/src/libs/components/page-layout/styles.module.css
- make sidebar width be same width on all pages and for all screen resolutions
> fix: The sidebar's size is inconsistent and changes when navigating between different sidebar links gf-475

- apps/backend/src/libs/modules/encryption/base-encryption.module.ts
- changed decryption function
(after reloading the project page, it returns a bad decrypted key, and if you copied it after reloading the page, the key changed to the wrong one.)
> fix: The "API key not found" is displayed in console after an attempt to setup the Analytics with a API key generated more than a day ago gf-495

- apps/backend/src/libs/helpers/helpers.ts
- apps/backend/src/modules/activity-logs/activity-log.service.ts
- apps/frontend/src/libs/helpers/helpers.ts
- apps/frontend/src/pages/analytics/analytics.tsx
- packages/shared/src/index.ts
- packages/shared/src/libs/helpers/get-end-of-day/get-end-of-day.helper.ts
- packages/shared/src/libs/helpers/get-start-of-day/get-start-of-day.helper.ts
- packages/shared/src/libs/helpers/helpers.ts
+ Added getEndOfDay helper.
+ Adjusted date format (omitting time) on frontend and backend.
First render earlier:
Now:
> fix: inconsistent data display on analytics table due to date format issue gf-510

- apps/frontend/src/pages/contributors/libs/helpers/get-contributor-columns/get-contributor-columns.helper.tsx
- increased size of "Do Not Track" column (130px -> 140px);
> fix: "Do Not Track" column text wraps onto two lines on smaller screen sizes gf-528

- packages/shared/src/libs/helpers/get-sync-time/get-sync-time.helper.ts
When the difference is 24 hours, the text "1 day ago" is displayed and displayed in red color
> fix: incorrect time display and color coding for analytics last sync time gf-547

- apps/frontend/src/libs/components/chart/chart.tsx
- apps/frontend/src/libs/hooks/use-search-filters/use-search-filters.hook.ts
- apps/frontend/src/pages/project/libs/components/contributor-card/contributor-card.tsx
* Browser Back button is now working after redirecting to the Analytics page on contributor item click.
* Added search preselected for contributor name.
* Fixed activity chart not clickable.
> fix: Browser Back button not functioning after redirecting to the Analytics page from the Project details page gf-540

- apps/backend/src/modules/contributors/contributor.controller.ts
- apps/frontend/src/modules/contributors/contributors-api.ts
- apps/frontend/src/modules/contributors/slices/actions.ts
- apps/frontend/src/modules/contributors/slices/contributor.slice.ts
- apps/frontend/src/modules/contributors/slices/contributors.ts
- apps/frontend/src/pages/contributors/contributors.tsx
- apps/frontend/src/pages/contributors/libs/components/contributor-merge-form/contributor-merge-form.tsx
* Added action to load all contributors without pagination.
* Refactored contributors page component to use it when merge modal is opened.
> fix: not all contributors are displayed in contributor merge form gf-550

- apps/backend/src/modules/project-groups/project-group.repository.ts
- package-lock.json
- Filtered project groups based on user permissions in findAllByUserId.
- Ensured that only project groups with correct permissions are considered when filtering projects.
- Users without sufficient permissions will no longer see unauthorized project cards, improving security and avoiding 404 errors.
> fix: restrict project card visibility based on user permissions gf-558

- apps/frontend/src/pages/project/project.tsx
- updated hasSetupAnalyticsPermission check;
> fix: the setup analytics button is not displayed on the page for user with edit project permission for the specific project gf-573

- apps/backend/src/modules/project-groups/project-group.service.ts
- rid of error throwing when project groups were not deleted by project id
> fix: Error notification appears when trying delete project which hasn't any project group gf-555

- apps/backend/src/modules/projects/project.controller.ts
- apps/frontend/src/pages/project/libs/components/project-details-menu/project-details-menu.tsx
- apps/frontend/src/pages/project/project.tsx
- package-lock.json
- Removed delete button showing for users with any of the Projectpermissions.
- Adjusted backend to limit deletion for users with Projectpermissions
> fix: the delete project button is displayed and the deletion is accessible for the manage specific project permission gf-570

- apps/frontend/src/pages/project/libs/components/setup-analytics-modal/setup-analytics-modal.tsx
- scripts/analytics/src/libs/helpers/execute-command/execute-command.helper.ts
- scripts/analytics/src/libs/modules/analytics-cli/base-analytics-cli.ts
- scripts/analytics/src/libs/modules/analytics-cli/init-analytics-cli.ts
- scripts/analytics/src/libs/modules/git-service/base-git-service.module.ts
- scripts/analytics/src/libs/modules/git-service/libs/types/git-service.type.ts
- scripts/analytics/src/libs/types/analytics-script-config.ts
- scripts/analytics/src/libs/types/types.ts
- scripts/analytics/src/modules/analytics/analytics.service.ts
> feat: change script to take parameters from configuration file instead of CLI gf-595
