- apps/frontend/src/assets/css/styles.css
- apps/frontend/src/assets/css/variables.css
This PR implements the common color variables from the design
> feat: add common color variables gf-27

- apps/frontend/src/libs/components/app/app.tsx
- apps/frontend/src/libs/components/components.ts
- apps/frontend/src/libs/components/loader/loader.tsx
- apps/frontend/src/libs/components/loader/styles.module.css
Implemented a loader component:
- pulsing animation (similar to https://www.davidhu.io/react-spinners/storybook/?path=/docs/puffloader--docs)
> feat: create loader component gf-9

- apps/frontend/src/index.tsx
- apps/frontend/src/libs/components/components.ts
- apps/frontend/src/libs/components/protected-route/protected-route.tsx
- apps/frontend/src/modules/auth/libs/types/types.ts
- apps/frontend/src/modules/auth/slices/auth.slice.ts
Summary
Created a ProtectedRoute wrapper component that redirects unauthorized users from protected pages to the Sign In page.
> feat: add route protection gf-14

- apps/frontend/src/assets/css/fonts.css
- The weigth 400 is Regular
- The weigth 500 is medium
> fix: change the weight of the fonts gf-1

- apps/backend/src/libs/modules/server-application/libs/constants/white-routes.constant.ts
- apps/backend/src/libs/plugins/authorization/authorization.plugin.ts
This PR fixes [https://github.com/BinaryStudioAcademy/bsa-2024-gitfit/pull/43](url)
- Adjust white routes constant
- Refactor token extraction to remove 'Bearer ' prefix
> fix: correct white routes constant and token extraction gf-13

- docs/specification.md
1. Added information about pagination elements in the "Contributors" table
2. Added notification about successful update of contributor information
> docs: add notification information 2-8 contributors gf-68

- docs/specification.md
- Add fields validation information
- Add info about Hide/Show password toggle
- All changes updated regarding to the suggestions received before
> docs: requirements update 2.3 Auth gf-63

- docs/specification.md
- add page access details
- describ page appearance for users with no certain permission
- add field validation info
> docs: requirement update access managment gf-64

- apps/backend/src/db/migrations/20240829181900_fix_user_groups_to_permissions.ts
- apps/frontend/src/libs/components/page-layout/styles.module.css
- apps/frontend/src/pages/access-management/styles.module.css
- apps/frontend/src/pages/projects/projects.tsx
- apps/frontend/src/pages/projects/styles.module.css
Changed the styles on the Access Management page
Changed styles in the PageLayout component
Changed the styles on the Project page for the title of this page
Projects page
Access Management page
> fix: Inconsistent layout on the Projects and Access Managment page gf-120

- apps/frontend/src/libs/components/header/libs/components/user-popover/styles.module.css
Changed font and set min width to 250px as in design.
> fix: the size of the user popup and the font of the elements don't match the layout gf-136

- apps/frontend/src/libs/components/header/header.tsx
- apps/frontend/src/libs/components/header/styles.module.css
Done: 
- Added navigation to root from logo
> feat: Logo element on the Header component should redirect user to the Main page gf-154

- apps/frontend/src/libs/components/breadcrumbs/styles.module.css
- apps/frontend/src/pages/project/project.tsx
- apps/frontend/src/pages/project/styles.module.css
Done:
- Added breadcrumbs to the project details page
Preview:
> feat: Add breadcrumbs to the project details page gf-165

- apps/frontend/src/libs/enums/notification-message.enum.ts
- changed message to "Your profile has been successfully updated."
> fix: The success message for profile update doesn`t match the specification gf-193

- apps/frontend/src/libs/hooks/use-pagination/libs/helpers/total-pages.helper.ts
- package-lock.json
Adjusted the table pagination to handle emty tables.
> fix: internal server error for table pagination on emty tables gf-205

- apps/backend/src/modules/users/user.service.ts
- package-lock.json
- packages/shared/src/libs/enums/exception-message.enum.ts
Summary:
- Changed the notification message
> fix: Change the text message on the Error toast notification when attempting to Sign Up with existing email gf-190

- apps/frontend/src/pages/projects/projects.tsx
- apps/frontend/src/pages/projects/styles.module.css
Summary:
- Add the message "No projects found matching your search criteria. Please try different keywords." if no results were found during the search on the "Projects" page.
> feat: Add a "No projects found" message when search field no results on the Projects page gf-187

- apps/frontend/src/libs/components/avatar/avatar.tsx
- apps/frontend/src/libs/components/avatar/styles.module.css
Changes:
- if an `imageSrc` is provided, an `<img>` tag is rendered; otherwise, the first letter of the name is displayed;
- used getValidClassNames to apply no-image class when no image is provided; 
- added border styling when no image is provided;
- fixed class name typo.
> feat: improve avatar visibility gf-202

- apps/backend/src/modules/groups/group.repository.ts
- apps/backend/src/modules/users/user.repository.ts
- add users list sorting by createdAt
> fix: The users are not sorted correctly at the "Users" table in the "Access Managment" page gf-290

- apps/frontend/src/pages/access-management/libs/helpers/get-group-columns.helper.tsx
- apps/frontend/src/pages/access-management/libs/helpers/get-group-rows.helper.tsx
- apps/frontend/src/pages/access-management/libs/types/group-row.type.ts
> feat: Add users column to the groups table gf-301

- apps/backend/src/modules/projects/project.entity.ts
- apps/backend/src/modules/projects/project.service.ts
- apps/frontend/src/pages/projects/libs/components/project-update-form/project-update-form.tsx
- apps/frontend/src/pages/projects/projects.tsx
- packages/shared/src/modules/projects/libs/types/project-get-all-item-response-dto.type.ts
Do not return project description from the backend on GET /projects endpoint
Changed getting the project in the modal edit window
> feat: not return description on get all request gf-259

- apps/frontend/src/pages/project/project.tsx
> fix: Button names don`t match the design in "Setup Analytics" gf-308

- apps/backend/src/modules/projects/project.controller.ts
- package-lock.json
- Updated the project creation endpoint to return `HTTPCode.CREATED (201)` instead of `HTTPCode.OK (200)` to correctly indicate resource creation.
- Modified the Swagger documentation to reflect the status code change.
> fix: adjusted httpcode to 201 created gf-312

- packages/shared/src/modules/users/libs/enums/user-validation-message.enum.ts
Changes:
- updated email validation message;
> feat: update validation message for email address field gf-314

- apps/backend/src/modules/project-groups/project-group.controller.ts
- apps/backend/src/modules/project-groups/project-group.repository.ts
- apps/backend/src/modules/project-groups/project-group.service.ts
- apps/frontend/src/libs/enums/notification-message.enum.ts
- apps/frontend/src/modules/project-groups/project-groups-api.ts
- apps/frontend/src/modules/project-groups/slices/actions.ts
- apps/frontend/src/modules/project-groups/slices/project-group.slice.ts
- apps/frontend/src/modules/project-groups/slices/project-groups.ts
- apps/frontend/src/pages/project-access-management/libs/components/components.ts
- apps/frontend/src/pages/project-access-management/libs/components/project-group-menu/project-group-menu.tsx
- apps/frontend/src/pages/project-access-management/libs/components/project-group-menu/styles.module.css
- apps/frontend/src/pages/project-access-management/libs/components/project-groups-table/project-groups-table.tsx
- apps/frontend/src/pages/project-access-management/libs/helpers/get-project-group-columns.helper.tsx
- apps/frontend/src/pages/project-access-management/project-access-management.tsx
- packages/shared/src/libs/enums/exception-message.enum.ts
Done:
- Added project group menu with Delete
- Added project group deleting logic to backand and frontend
Preview:
> feat: Add an ability to delete project group gf-353

- apps/frontend/src/modules/project-groups/slices/actions.ts
- apps/frontend/src/pages/project-access-management/libs/components/project-group-create-form/project-group-create-form.tsx
- apps/frontend/src/pages/project-access-management/libs/components/project-group-form/project-group-form.tsx
- apps/frontend/src/pages/project-access-management/libs/components/project-group-users-table/libs/components/components.ts
- apps/frontend/src/pages/project-access-management/libs/components/project-group-users-table/libs/components/project-group-users-search/project-group-users-search.tsx
- apps/frontend/src/pages/project-access-management/libs/components/project-group-users-table/libs/components/project-group-users-search/styles.module.css
- apps/frontend/src/pages/project-access-management/libs/components/project-group-users-table/project-group-users-table.tsx
- apps/frontend/src/pages/project-access-management/project-access-management.tsx
Add search input to users table on create project group modal.
> feat: add search input to users table in modal gf-355

- apps/frontend/src/libs/helpers/helpers.ts
- apps/frontend/src/pages/projects/libs/components/project-card/project-card.tsx
- packages/shared/src/index.ts
- packages/shared/src/libs/helpers/get-start-of-day/get-start-of-day.helper.ts
- packages/shared/src/libs/helpers/helpers.ts
- created a new helper `getStartOfDay` (wrapper around `startOfDay` from "date-fns");
- wrapped creating dates in `ProjectCard` with this helper.
> feat: handle dates that cross into the next day but are less than 24 hours apart gf-274

- apps/frontend/src/libs/enums/notification-message.enum.ts
- apps/frontend/src/libs/modules/store/libs/types/root-reducer.type.ts
- apps/frontend/src/libs/modules/store/store.module.ts
- apps/frontend/src/modules/scripts/scripts.ts
- apps/frontend/src/modules/scripts/slices/actions.ts
- apps/frontend/src/modules/scripts/slices/scripts.slice.ts
- apps/frontend/src/modules/scripts/slices/scripts.ts
- apps/frontend/src/pages/project/libs/components/setup-analytics-modal/setup-analytics-modal.tsx
- apps/frontend/src/pages/project/libs/components/setup-analytics-modal/styles.module.css
* Updated analytics instructions.
* Updated margins to not have scroll in modal on full hd displays.
* Created scripts frontend module.
> feat: Update analytics instructions with the new flow gf-406

- apps/frontend/src/libs/modules/api/base-http-api.ts
- apps/frontend/src/libs/modules/http/http.ts
- apps/frontend/src/libs/modules/http/libs/enums/enums.ts
- apps/frontend/src/libs/modules/http/libs/enums/exception-name.enum.ts
- apps/frontend/src/libs/modules/http/libs/exceptions/exceptions.ts
- apps/frontend/src/libs/modules/http/libs/exceptions/unauthorized-error.exception.ts
- apps/frontend/src/libs/modules/store/libs/middlewares/handle-unauthorized-error.middleware.ts
- apps/frontend/src/libs/modules/store/libs/middlewares/middlewares.ts
- apps/frontend/src/libs/modules/store/store.module.ts
- apps/frontend/src/libs/modules/store/store.ts
- created `UnauthorizedError`
- run logout dispatch in `handleUnauthorizedError`
> feat: Log out user when 401 error occurs gf-343

- apps/frontend/src/pages/project/libs/components/contributor-card/contributor-card.tsx
Fixed contributor last activity date to start from the beginning of the day.
> fix: change contributors last activity count to start from the begginning of the day gf-446

- apps/frontend/src/pages/project-access-management/libs/components/project-group-create-form/project-group-create-form.tsx
- apps/frontend/src/pages/project-access-management/libs/components/project-group-update-form/project-group-update-form.tsx
- changed "Submit" label to proper ones
> fix: The submission button for the Create Project Group modal has inconsistent to the mockup text gf-474

- apps/frontend/src/pages/project/libs/components/contributor-card/styles.module.css
- apps/frontend/src/pages/projects/libs/components/project-card/styles.module.css
- package-lock.json
Adjusted style so both have matching card sizes and typography
> fix: adjusted project/contributor card style to match figma design gf-506

- apps/frontend/src/libs/components/header/libs/components/notifications-popover/notifications-popover.tsx
- package-lock.json
- Adjusted the loader to show when loading. 
- Adjusted placeholder to only show when no items and not loading. 
Notifications with throttle
https://github.com/user-attachments/assets/f3411431-13fb-4f56-a5fc-91a5c28a2791
No notifications
https://github.com/user-attachments/assets/4d28f34f-08b5-4af2-b738-45beae2371a9
> fix: adjusted loader and placeholder to render properly when loading gf-515

- apps/frontend/src/modules/contributors/slices/contributor.slice.ts
- apps/frontend/src/pages/contributors/contributors.tsx
- apps/frontend/src/pages/project/project.tsx
- reloads on Contributors page
- reloads in Project page + close update, merge and split modals only on fulfilled
> fix: reload contributors lists on split gf-519

- apps/frontend/src/pages/analytics/analytics.tsx
- apps/frontend/src/pages/analytics/libs/components/analytics-table/analytics-table.tsx
- apps/frontend/src/pages/analytics/libs/constants/constants.ts
- added dynamic emptyPlaceholder message based on hasSearch check;
- updated <Table> to use the emptyPlaceholderMessage.
> fix: incorrect message displayed when all contributors are hidden gf-538

- readme.md
- added `dateTime last_activity_date` to the `projects` table;
- modified projects name to `varchar name UK` to show uniqueness;
- added `varchar encrypted_key UK` to the project_api_keys table;
- changed `activity_logs` `date` from `date` to `dateTime`.
> feat: update schema in readme to match the app gf-543

- apps/backend/src/modules/users/user.repository.ts
- add project groups to sign in response
screenshot after login:
> fix: Pending Access message is displayed for a user with access to view a specific project gf-560

- packages/shared/src/modules/users/libs/validation-schemas/user-patch.validation-schema.ts
* Updated user patch validation schema.
> fix: Name field allows special characters, numbers, Cyrillic in Profile Update gf-562

- apps/frontend/src/modules/project-groups/slices/actions.ts
- update auth user permissions after project group deleted
> fix: Incorrect access display after deleting a group the user belongs to gf-585
